export type LoopLength = "1m" | "2m" | "4m";

export const CHANNEL_NAMES = [
  "Perc2",
  "Perc1",
  "OpenHat",
  "ClosedHat",
  "Snare",
  "Clap",
  "Kick2",
  "Kick1",
] as const;
export type ChannelNames = typeof CHANNEL_NAMES;
export type ChannelName = (typeof CHANNEL_NAMES)[number];

export const SAMPLES: Record<ChannelName, string[]> = {
  Perc2: [
    "P_Woing",
    "P_Tube",
    "P_Tick",
    "P_Taka",
    "P_Steamers",
    "P_ShortTom",
    "P_Sazz",
    "P_Rim",
    "P_ReverseHat",
    "P_MiniBongo",
    "P_MidTom",
    "P_Cow",
    "P_Tok",
    "P_Knock",
  ],
  Perc1: [
    "P_Knock",
    "P_Tok",
    "P_Burial",
    "P_Cow",
    "P_MidTom",
    "P_MiniBongo",
    "P_ReverseHat",
    "P_Rim",
    "P_Sazz",
    "P_ShortTom",
    "P_Steamers",
    "P_Taka",
    "P_Tick",
    "P_Tube",
    "P_Woing",
  ],
  OpenHat: [
    "OH_909",
    "OH_Coast",
    "OH_Light",
    "OH_NuDisco",
    "OH_Sizzle",
    "OH_Squal",
    "OH_Taka",
    "OH_Tech",
    "OH_909B",
    "OH_909C",
    "OH_Techno",
  ],
  ClosedHat: [
    "CH_Tick",
    "CH_Real",
    "CH_Cut",
    "CH_Classic",
    "CH_Sitch",
    "CH_Subtle",
  ],
  Snare: [
    "S_Wick",
    "S_March",
    "S_Disco",
    "S_Pap",
    "S_Punch",
    "S_Verb",
    "S_Alien",
  ],
  Clap: [
    "C_Chuck",
    "C_Kerplap",
    "C_Nautilus",
    "C_Slock",
    "C_Spank",
    "C_Slap",
    "C_Kash",
  ],
  Kick2: ["K2_Thump", "K2_Short", "K2_Vinyl", "K2_Tonic", "K2_Rudebot"],
  Kick1: [
    "K1_Coffee",
    "K1_Peggy",
    "K1_Mouse",
    "K1_Charlotte",
    "K1_Thunk",
    "K1_Hard",
    "K1_Leftfield",
  ],
};
